services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - trustchain-postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'trustchain-saas']
      interval: 5s
      timeout: 10s
      retries: 5

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  trustchain-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      sdm-backend:
        condition: service_healthy

  sdm-backend:
    build:
      context: ../sdm-backend
      dockerfile: Dockerfile
    container_name: sdm-backend
    ports:
      - ${SDM_BACKEND_PORT}:${SDM_BACKEND_PORT}
  
volumes:
  trustchain-postgres-db:
