version: '3'

services:
  webserver:
    image: nginx:mainline-alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - trustchain
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./index.html:/var/www/html/index.html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - trustchain
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email hello@trustchain.network --agree-tos --no-eff-email --staging -d trustchain.network  -d www.trustchain.network 

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/trustchain-monorepo/packages/letsencrypt/
      o: bind
networks:
  trustchain:
